# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/test'
    commandOptions: '-var client_id=$(- task: DownloadSecureFile@1

  inputs:
    secureFile: 'azure_rsa.pub') -var client_secret=$(client_secret) -var ssh_public_key= $(publickey.secureFilePath)'
    backendServiceArm: 'azure-resource-manager-service-conn'
    backendAzureRmResourceGroupName: 'sample'
    backendAzureRmStorageAccountName: 'sample_storage'
    backendAzureRmContainerName: 'sample_container'
    backendAzureRmKey: 'kubernetes-dev.tf'